kind: pipeline
name: development

steps:
  - name: Check coding style
    pull: never
    image: drone/base:golangci-lint
    depends_on: [ clone ]
    commands:
      - golangci-lint run ./...
    volumes:
      - name: ssh_key
        path: /root/.ssh

  - name: Unit test and build
    pull: never
    image: drone/base:gotest
    depends_on: [ clone ]
    commands:
      - gotestsum ./... -v -cover -race
      - make
    volumes:
      - name: ssh_key
        path: /root/.ssh

volumes:
  - name: ssh_key
    host:
      path: /root/.ssh
